package Apackage;


import ControlPackage.CBobot;
import ControlPackage.CInisialisasi;
import ControlPackage.CInput;
import ControlPackage.CPembelajaran;
import ControlPackage.CPengujian;
import ControlPackage.CTarget;
import EntitasPackage.BackPropogation;
import EntitasPackage.DataInisialisasi;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gilbert
 */
public class FormAplikasi extends javax.swing.JFrame {

    /**
     * Creates new form FrameAplikasi
     */
    String fileNameMasukanPembelajaran;
    String fileNameMasukanTargetPembelajaran;
    String fileNameMasukanPengujian;
    String fileNameMasukanTargetPengujian;
    
    private DefaultTableModel model;
   
    private Object[] rowData;
    private int cols ;
    private int rows ;
    private File csvFileMasukan, fileBobotVToSave,fileBobotWToSave,fileBobotMaksToSave, fileHasilPengujianToSave, fileTingkatAkurasiToSave;
    String[] columnNamesInput = {"Bulan","Tahun","Jabotabek","Non Jabotabek","Sumatera","Total Penumpang"};
    String columnNameTarget = "Total Penumpang";
    BufferedWriter bufferedWriter;
    
    CInisialisasi KInisialisasi;
    CInput Kinput;
    CTarget KTarget;
    CPembelajaran kPembelajaran;
    CBobot kBobot;
    CPengujian kPengujian;
    
    
    public FormAplikasi() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        initData();
        kBobot = new CBobot();
        Kinput = new CInput();
        KTarget = new CTarget();
        kPengujian = new CPengujian();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel8 = new javax.swing.JPanel();
        fileChooserOpenFileMasukan = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileChooserSaveBoborV = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        labelKecepatanBelajar = new javax.swing.JLabel();
        labelMinimumError = new javax.swing.JLabel();
        labelHiddenLayer = new javax.swing.JLabel();
        textFieldKecepatanBelajar = new javax.swing.JTextField();
        textFieldMinimumError = new javax.swing.JTextField();
        textFieldHiddenLayer = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonKosongkan = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        textFieldLocationMasukanPembelajaran = new javax.swing.JTextField();
        buttonBukaLocationMasukanPembelajaran = new javax.swing.JButton();
        buttonNext1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaMasukanPembelajaran = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        textFieldLocationMasukanTarget = new javax.swing.JTextField();
        buttonBukaLocationMasukanTarget = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaTargetPembelajaran = new javax.swing.JTextArea();
        buttonNext2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        buttonNext3 = new javax.swing.JButton();
        labelBobotV = new javax.swing.JLabel();
        textFieldBobotV = new javax.swing.JTextField();
        labelBobotW = new javax.swing.JLabel();
        textFieldBobotW = new javax.swing.JTextField();
        buttonSimpanBobotV = new javax.swing.JButton();
        buttonSimpanBobotW = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        labelJumlahIterasi = new javax.swing.JLabel();
        labelError = new javax.swing.JLabel();
        textFieldJumlahIterasi = new javax.swing.JTextField();
        textFieldError = new javax.swing.JTextField();
        buttonProses = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        labelBobotV1 = new javax.swing.JLabel();
        textFieldBobotVPengujian = new javax.swing.JTextField();
        labelBobotW1 = new javax.swing.JLabel();
        textFieldBobotWPengujian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonNext4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        textFieldDataMasukanPengujian = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaMasukanPengujian = new javax.swing.JTextArea();
        buttonNext5 = new javax.swing.JButton();
        buttonDataMasukanPengujian = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        buttonNext6 = new javax.swing.JButton();
        textFieldDataTargetPengujian = new javax.swing.JTextField();
        buttonDataTargetPengujian = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaTargetPengujian = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonProsesPengujian = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        textAreaHasilPengujian = new javax.swing.JTextArea();
        textFieldLokasiDataHasilPengujian = new javax.swing.JTextField();
        buttonSimpanDataHasilPengujian1 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Prediksi Jumlah Penumpang Kereta Api di Indonesia");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setPreferredSize(new java.awt.Dimension(430, 300));

        labelKecepatanBelajar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKecepatanBelajar.setText("Learning Rate                :");

        labelMinimumError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimumError.setText("Minimum Error               :");

        labelHiddenLayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHiddenLayer.setText("Hidden Layer                :");

        textFieldKecepatanBelajar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldKecepatanBelajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldKecepatanBelajarActionPerformed(evt);
            }
        });

        textFieldMinimumError.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textFieldHiddenLayer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonKosongkan.setText("Kosongkan");
        buttonKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKosongkanActionPerformed(evt);
            }
        });

        buttonNext.setText("Berikutnya");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(labelMinimumError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelKecepatanBelajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(labelHiddenLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldKecepatanBelajar)
                            .addComponent(textFieldMinimumError)
                            .addComponent(textFieldHiddenLayer)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91)
                        .addComponent(buttonKosongkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58)))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKecepatanBelajar)
                    .addComponent(textFieldKecepatanBelajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMinimumError)
                    .addComponent(textFieldMinimumError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHiddenLayer)
                    .addComponent(textFieldHiddenLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonKosongkan))
                .addGap(41, 41, 41)
                .addComponent(buttonNext)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inisialisasi", jPanel4);

        textFieldLocationMasukanPembelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLocationMasukanPembelajaranActionPerformed(evt);
            }
        });

        buttonBukaLocationMasukanPembelajaran.setText("Buka");
        buttonBukaLocationMasukanPembelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBukaLocationMasukanPembelajaranActionPerformed(evt);
            }
        });

        buttonNext1.setText("Berikutnya");
        buttonNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext1ActionPerformed(evt);
            }
        });

        textAreaMasukanPembelajaran.setColumns(20);
        textAreaMasukanPembelajaran.setRows(5);
        jScrollPane2.setViewportView(textAreaMasukanPembelajaran);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(textFieldLocationMasukanPembelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonBukaLocationMasukanPembelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLocationMasukanPembelajaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBukaLocationMasukanPembelajaran))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonNext1)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Data Masukan Pembelajaran", jPanel5);

        textFieldLocationMasukanTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLocationMasukanTargetActionPerformed(evt);
            }
        });

        buttonBukaLocationMasukanTarget.setText("Buka");
        buttonBukaLocationMasukanTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBukaLocationMasukanTargetActionPerformed(evt);
            }
        });

        textAreaTargetPembelajaran.setColumns(20);
        textAreaTargetPembelajaran.setRows(5);
        jScrollPane3.setViewportView(textAreaTargetPembelajaran);

        buttonNext2.setText("Berikutnya");
        buttonNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldLocationMasukanTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonBukaLocationMasukanTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLocationMasukanTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBukaLocationMasukanTarget))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(buttonNext2)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGap(43, 43, 43)))
        );

        jTabbedPane2.addTab("Data Target Pembelajaran", jPanel6);

        buttonNext3.setText("Berikutnya");
        buttonNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext3ActionPerformed(evt);
            }
        });

        labelBobotV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBobotV.setText("Bobot V");

        textFieldBobotV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBobotVActionPerformed(evt);
            }
        });

        labelBobotW.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBobotW.setText("Bobot W");

        buttonSimpanBobotV.setText("Simpan");
        buttonSimpanBobotV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanBobotVActionPerformed(evt);
            }
        });

        buttonSimpanBobotW.setText("Simpan");
        buttonSimpanBobotW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanBobotWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBobotV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBobotW)
                            .addComponent(textFieldBobotW)
                            .addComponent(textFieldBobotV, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSimpanBobotV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSimpanBobotW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonNext3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBobotV)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBobotV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpanBobotV))
                .addGap(18, 18, 18)
                .addComponent(labelBobotW)
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBobotW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpanBobotW))
                .addGap(18, 18, 18)
                .addComponent(buttonNext3)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Data Bobot Hasil Pembelajaran", jPanel7);

        labelJumlahIterasi.setText("Jumlah Iterasi   :");

        labelError.setText("Error                 :");

        buttonProses.setText("Proses");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonProses)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(labelJumlahIterasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldJumlahIterasi)
                            .addComponent(textFieldError))))
                .addGap(128, 128, 128))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlahIterasi)
                    .addComponent(textFieldJumlahIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelError)
                    .addComponent(textFieldError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(buttonProses)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Proses Pembelajaran", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Pembelajaran", jPanel1);

        labelBobotV1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBobotV1.setText("Bobot V");

        labelBobotW1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBobotW1.setText("Bobot W");

        jButton1.setText("Buka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buka");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonNext4.setText("Berikutnya");
        buttonNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldBobotWPengujian, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                            .addComponent(labelBobotW1)
                            .addComponent(labelBobotV1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldBobotVPengujian))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNext4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelBobotV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBobotVPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(labelBobotW1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldBobotWPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(buttonNext4)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Data Bobot Hasil Pembelajaran", jPanel10);

        textAreaMasukanPengujian.setColumns(20);
        textAreaMasukanPengujian.setRows(5);
        jScrollPane4.setViewportView(textAreaMasukanPengujian);

        buttonNext5.setText("Berikutnya");
        buttonNext5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext5ActionPerformed(evt);
            }
        });

        buttonDataMasukanPengujian.setText("Buka");
        buttonDataMasukanPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataMasukanPengujianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 479, Short.MAX_VALUE)
                        .addComponent(buttonNext5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(textFieldDataMasukanPengujian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDataMasukanPengujian)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDataMasukanPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDataMasukanPengujian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNext5))
        );

        jTabbedPane3.addTab("Data Masukan Pengujian", jPanel11);

        buttonNext6.setText("Berikutnya");
        buttonNext6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNext6ActionPerformed(evt);
            }
        });

        buttonDataTargetPengujian.setText("Buka");
        buttonDataTargetPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataTargetPengujianActionPerformed(evt);
            }
        });

        textAreaTargetPengujian.setColumns(20);
        textAreaTargetPengujian.setRows(5);
        jScrollPane5.setViewportView(textAreaTargetPengujian);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 479, Short.MAX_VALUE)
                        .addComponent(buttonNext6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(textFieldDataTargetPengujian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDataTargetPengujian)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDataTargetPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDataTargetPengujian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(buttonNext6))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addGap(29, 29, 29)))
        );

        jTabbedPane3.addTab("Data Target", jPanel12);

        jLabel1.setText("Hasil Pengujian");

        buttonProsesPengujian.setText("Proses");
        buttonProsesPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesPengujianActionPerformed(evt);
            }
        });

        textAreaHasilPengujian.setColumns(20);
        textAreaHasilPengujian.setRows(5);
        jScrollPane6.setViewportView(textAreaHasilPengujian);

        textFieldLokasiDataHasilPengujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldLokasiDataHasilPengujianActionPerformed(evt);
            }
        });

        buttonSimpanDataHasilPengujian1.setText("Simpan");
        buttonSimpanDataHasilPengujian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanDataHasilPengujian1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(buttonProsesPengujian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(312, 312, 312))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldLokasiDataHasilPengujian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSimpanDataHasilPengujian1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(buttonProsesPengujian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldLokasiDataHasilPengujian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpanDataHasilPengujian1))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Proses Pengujian", jPanel14);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pengujian", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldKecepatanBelajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldKecepatanBelajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldKecepatanBelajarActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        double learningRate,minError;
        int hiddenLayer;    
        
        if (textFieldKecepatanBelajar.getText().equals("")|| 
                textFieldMinimumError.getText().equals("")||
                textFieldHiddenLayer.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Data tidak lengkap!","Error",
                    JOptionPane.ERROR_MESSAGE);  
        }
        else{
            int layerMasukan = 6;
            int layerKeluaran=1;
            learningRate = Double.parseDouble(textFieldKecepatanBelajar.getText());
            minError  = Double.parseDouble(textFieldMinimumError.getText());
            hiddenLayer = Integer.parseInt(textFieldHiddenLayer.getText());
        
            KInisialisasi = new CInisialisasi(layerMasukan,layerKeluaran,learningRate,minError,hiddenLayer);
            KInisialisasi.simpanInisialisasi(layerMasukan,layerKeluaran,learningRate, minError, hiddenLayer);
            JOptionPane.showMessageDialog(null,"Data disimpan!");
            
        }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKosongkanActionPerformed
        // TODO add your handling code here:
        textFieldHiddenLayer.setText("");
        textFieldKecepatanBelajar.setText("");
        textFieldMinimumError.setText("");
        
    }//GEN-LAST:event_buttonKosongkanActionPerformed

    private void textFieldLocationMasukanPembelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLocationMasukanPembelajaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLocationMasukanPembelajaranActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonBukaLocationMasukanPembelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBukaLocationMasukanPembelajaranActionPerformed
        // TODO add your handling code here:
        textAreaMasukanPembelajaran.setText("");
        if (!(choose.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)) {
            return;
        }
        csvFileMasukan = choose.getSelectedFile();
        if (csvFileMasukan == null)
        {
            return;
        }
        fileNameMasukanPembelajaran = csvFileMasukan.getAbsolutePath();
        textFieldLocationMasukanPembelajaran.setText(fileNameMasukanPembelajaran);
        //parseCSV();
        
        Kinput.setDataInput1(fileNameMasukanPembelajaran);
        rows = Kinput.getJumlahBarisPembelajaran();
        cols = Kinput.getJumlahKolomPembelajaran();
        Object[][] dataPembelajaran = new Double[rows][cols];
       
         for (int i = 0; i < 6; i++){
             textAreaMasukanPembelajaran.append(columnNamesInput[i]+"\t\t");
         }
        textAreaMasukanPembelajaran.append("\n");
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                dataPembelajaran[i][j]= Kinput.getDataInputPembelajaran(i, j);
                double dp1 = (double) dataPembelajaran[i][j];
                int dtPembelajaran = (int) dp1;
                textAreaMasukanPembelajaran.append(String.valueOf(dtPembelajaran)+"\t\t");  
//                textAreaMasukanPembelajaran.append(String.valueOf(dataPembelajaran[i][j])+"\t");  
            }
            textAreaMasukanPembelajaran.append("\n");
            
        }
        
        
    }//GEN-LAST:event_buttonBukaLocationMasukanPembelajaranActionPerformed

    private void buttonNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_buttonNext1ActionPerformed

    private void textFieldLocationMasukanTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLocationMasukanTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLocationMasukanTargetActionPerformed

    private void buttonBukaLocationMasukanTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBukaLocationMasukanTargetActionPerformed
        // TODO add your handling code here:
        textAreaTargetPembelajaran.setText("");
        if (!(choose.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)) {
            return;
        }
        csvFileMasukan = choose.getSelectedFile();
        if (csvFileMasukan == null)
        {
            return;
        }
        fileNameMasukanTargetPembelajaran = csvFileMasukan.getAbsolutePath();
        textFieldLocationMasukanTarget.setText( fileNameMasukanTargetPembelajaran);
        //textFieldLocationMasukanTarget.setText("assasas");
        
        KTarget.setDataTarget1(fileNameMasukanTargetPembelajaran);
        rows = KTarget.getJumlahBarisTargetPembelajaran();
        cols = KTarget.getJumlahKolomTargetPembelajaran();
        Object[][] dataTarget = new Double[rows][cols];
        textAreaTargetPembelajaran.append(columnNameTarget+"\n");
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                dataTarget[i][j]= KTarget.getDataTargetPembelajaran(i, j);
                double dt1 = (double) dataTarget[i][j];
                int dtTarget = (int) dt1;
//                textAreaTargetPembelajaran.append(String.valueOf(dataTarget[i][j])+"\t");  
                textAreaTargetPembelajaran.append(String.valueOf(dtTarget)+"\t"); 
            }
            textAreaTargetPembelajaran.append("\n");
        }
    }//GEN-LAST:event_buttonBukaLocationMasukanTargetActionPerformed

    private void buttonNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
    }//GEN-LAST:event_buttonNext2ActionPerformed

    private void buttonNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext3ActionPerformed
        // TODO add your handling code here:
        
        
//        System.out.println(kBobot.getNamaFileBobotV());
//        System.out.println(kBobot.getNamaFileBobotW());
//        System.out.println(kBobot.getNamaFileBobotMaks());
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_buttonNext3ActionPerformed

    private void buttonSimpanBobotVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanBobotVActionPerformed
        // TODO add your handling code here:
        if (saveFile.showSaveDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            fileBobotVToSave = saveFile.getSelectedFile();
            boolean isFile  = false;
            if (!fileBobotVToSave.exists()){
                try {
                    isFile = fileBobotVToSave.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(FormAplikasi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            textFieldBobotV.setText(fileBobotVToSave.getAbsolutePath());
        }
        
        CBobot.setNamaFileBobotV(textFieldBobotV.getText());
    }//GEN-LAST:event_buttonSimpanBobotVActionPerformed

    private void buttonSimpanBobotWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanBobotWActionPerformed
        // TODO add your handling code here:
        if (saveFile.showSaveDialog(this)== JFileChooser.APPROVE_OPTION)
        {
            fileBobotWToSave = saveFile.getSelectedFile();
            boolean isFile  = false;
            if (!fileBobotWToSave.exists()){
                try {
                    isFile = fileBobotWToSave.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(FormAplikasi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            textFieldBobotW.setText(fileBobotWToSave.getAbsolutePath());
        }
//        kBobot = new CBobot();
        CBobot.setNamaFileBobotW(textFieldBobotW.getText());
    }//GEN-LAST:event_buttonSimpanBobotWActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        // TODO add your handling code here:
        kPembelajaran = new CPembelajaran();
        
        CBobot.setLayerTersembunyi(Integer.parseInt(textFieldHiddenLayer.getText()));
        
        kPembelajaran.prosesPelatihan();
        textFieldJumlahIterasi.setText(String.valueOf(this.kPembelajaran.getTotalIterasi()));
        textFieldError.setText(String.valueOf(this.kPembelajaran.getError()));
        
        textFieldBobotVPengujian.setText(CBobot.getNamaFileBobotV());
        textFieldBobotWPengujian.setText(CBobot.getNamaFileBobotW());
        
                
    }//GEN-LAST:event_buttonProsesActionPerformed

    private void textFieldBobotVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBobotVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBobotVActionPerformed

    private void buttonSimpanDataHasilPengujian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanDataHasilPengujian1ActionPerformed
        // TODO add your handling code here:
        if (saveFile.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            fileHasilPengujianToSave = saveFile.getSelectedFile();
            boolean isFile = false;
            if (!fileHasilPengujianToSave.exists()){
                try {
                    isFile = fileHasilPengujianToSave.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(FormAplikasi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            textFieldLokasiDataHasilPengujian.setText(fileHasilPengujianToSave.getAbsolutePath());

        }
        kPengujian.simpanHasilUji(textFieldLokasiDataHasilPengujian.getText());
    }//GEN-LAST:event_buttonSimpanDataHasilPengujian1ActionPerformed

    private void textFieldLokasiDataHasilPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldLokasiDataHasilPengujianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldLokasiDataHasilPengujianActionPerformed

    private void buttonProsesPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesPengujianActionPerformed
        // TODO add your handling code here:
        CBobot.setNamaFileBobotV(textFieldBobotVPengujian.getText());
        CBobot.setNamaFileBobotW(textFieldBobotWPengujian.getText());
        

        this.kPengujian.setNamaFileHasilPengujian(textFieldLokasiDataHasilPengujian.getText());
        

        this.kPengujian.uji();
        this.kPengujian.formatHasil();

        textAreaHasilPengujian.append("Data Target \t\tData Prediksi\t\tTingkat Akurasi\n");

        for (int i = 1; i <= CTarget.getJumlahBarisTargetPengujian(); i++) {
            for (int j = 1; j <=CTarget.getJumlahKolomTargetPengujian(); j++) {
                double dataTarget = this.kPengujian.getDataTargetPengujian(i);
                double dataKeluaran = this.kPengujian.getKeluaran(i,j);
                int dtTarget = (int) dataTarget;
                int dtKeluaran = (int) dataKeluaran;
                textAreaHasilPengujian.append(String.valueOf(dtTarget+"\t\t"+
                    dtKeluaran + "\t\t" + this.kPengujian.getTingkatAkurasi(i)+"% \n"));
//                textAreaHasilPengujian.append(String.valueOf(this.kPengujian.getDataTargetPengujian(i)+"\t\t"+
//                    this.kPengujian.getKeluaran(i,j) + "\t\t" + this.kPengujian.getTingkatAkurasi(i)+"% \n"));
        }
        }

    }//GEN-LAST:event_buttonProsesPengujianActionPerformed

    private void buttonDataTargetPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataTargetPengujianActionPerformed
        // TODO add your handling code here:
        textAreaTargetPengujian.setText("");
        if (!(choose.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)) {
            return;
        }
        csvFileMasukan = choose.getSelectedFile();
        if (csvFileMasukan == null)
        {
            return;
        }
        fileNameMasukanTargetPengujian = csvFileMasukan.getAbsolutePath();
        textFieldDataTargetPengujian.setText(fileNameMasukanTargetPengujian);
        KTarget.setDataTarget2(fileNameMasukanTargetPengujian);
        rows = KTarget.getJumlahBarisTargetPengujian();
        cols = KTarget.getJumlahKolomTargetPengujian();
        //        System.out.println(rows+ " "+cols);
        Object[][] dataTargetPengujian = new Double[rows][cols];
        textAreaTargetPengujian.append(columnNameTarget+"\n");
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                dataTargetPengujian[i][j] = KTarget.getDataTargetPengujian(i, j);
                double dp1 = (double) dataTargetPengujian[i][j];
                int dtTargetPengujian = (int) dp1;
                textAreaTargetPengujian.append(String.valueOf(dtTargetPengujian));
            }
            textAreaTargetPengujian.append("\n");
        }
    }//GEN-LAST:event_buttonDataTargetPengujianActionPerformed

    private void buttonNext6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(3);
    }//GEN-LAST:event_buttonNext6ActionPerformed

    private void buttonDataMasukanPengujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataMasukanPengujianActionPerformed
        // TODO add your handling code here:
        textAreaMasukanPengujian.setText("");
        if (!(choose.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)) {
            return;
        }
        csvFileMasukan = choose.getSelectedFile();
        if (csvFileMasukan == null)
        {
            return;
        }
        fileNameMasukanPengujian = csvFileMasukan.getAbsolutePath();
        textFieldDataMasukanPengujian.setText(fileNameMasukanPengujian);
        Kinput.setDataInput2(fileNameMasukanPengujian);
        rows = Kinput.getJumlahBarisPengujian();
        cols = Kinput.getJumlahKolomPengujian();
        Object[][] dataMasukanPengujian= new Double[rows][cols];
        for (int i = 0; i < 6; i++) {
            textAreaMasukanPengujian.append(columnNamesInput[i]+"\t\t");
        }
        textAreaMasukanPengujian.append("\n");
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                dataMasukanPengujian[i][j] = Kinput.getDataInputPengujian(i, j);
                                double dp1 = (double) dataMasukanPengujian[i][j];
                                int dtMasukanPengujian = (int) dp1;
                //textAreaMasukanPengujian.append(String.valueOf(dataMasukanPengujian[i][j]+"\t\t"));
                                textAreaMasukanPengujian.append(String.valueOf(dtMasukanPengujian+"\t\t"));
            }
            textAreaMasukanPengujian.append("\n");
        }

    }//GEN-LAST:event_buttonDataMasukanPengujianActionPerformed

    private void buttonNext5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(2);
    }//GEN-LAST:event_buttonNext5ActionPerformed

    private void buttonNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNext4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane3.setSelectedIndex(1);
    }//GEN-LAST:event_buttonNext4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           
        if (!(choose.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)) {
            return;
        }
        csvFileMasukan = choose.getSelectedFile();
        if (csvFileMasukan == null)
        {
            return;
        }
        String fileBobotVPembelajaran = csvFileMasukan.getAbsolutePath();
        textFieldBobotVPengujian.setText(fileBobotVPembelajaran);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (!(choose.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)) {
            return;
        }
        csvFileMasukan = choose.getSelectedFile();
        if (csvFileMasukan == null)
        {
            return;
        }
        String fileBobotWPembelajaran = csvFileMasukan.getAbsolutePath();
        textFieldBobotWPengujian.setText(fileBobotWPembelajaran);
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private JFileChooser saveFile = new JFileChooser() 
     {
          {
               setFileFilter(new javax.swing.filechooser.FileFilter() 
               {
                    //@Override
                    public boolean accept(File f) 
                    {
                         if (f == null) return false;
                    if (f.isDirectory()) return true;
                    return f.getName().toLowerCase().endsWith("txt");
                    }
                    //@Override
                    public String getDescription() 
                    {
                         return "Text File  (*txt)";
                    }
               });
     }
    };      
        
    
     private JFileChooser choose = new JFileChooser() 
     {
          {
               setFileFilter(new javax.swing.filechooser.FileFilter() 
               {
                    //@Override
                    public boolean accept(File f) 
                    {
                         return f.getName().toLowerCase().endsWith("csv");
                    }
                    //@Override
                    public String getDescription() 
                    {
                         return "CSV-File";
                    }
               });
               
     }
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAplikasi().setVisible(true);

                        
            }
        });
        
        
    }

    private void initData()
    {   String[] test = new String[5];
        try {
            File file = new File ("Inisialisasi.txt");
            FileReader fileReader = new FileReader(file);
            BufferedReader br =  new BufferedReader(fileReader);
            
            ArrayList<String> list = new ArrayList<>();
            
            while (true){
                String line = br.readLine();
                if (line == null) {
                    break;
                }
                list.add(line);
            }
            
            for (int i = 0; i < 5; i++) {
                test[i] = list.get(i);
            }
            
            textFieldKecepatanBelajar.setText(test[2]);
            textFieldMinimumError.setText(test[3]);
            textFieldHiddenLayer.setText(test[4]);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormAplikasi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormAplikasi.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }
    
    
       
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBukaLocationMasukanPembelajaran;
    private javax.swing.JButton buttonBukaLocationMasukanTarget;
    private javax.swing.JButton buttonDataMasukanPengujian;
    private javax.swing.JButton buttonDataTargetPengujian;
    private javax.swing.JButton buttonKosongkan;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonNext1;
    private javax.swing.JButton buttonNext2;
    private javax.swing.JButton buttonNext3;
    private javax.swing.JButton buttonNext4;
    private javax.swing.JButton buttonNext5;
    private javax.swing.JButton buttonNext6;
    private javax.swing.JButton buttonProses;
    private javax.swing.JButton buttonProsesPengujian;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonSimpanBobotV;
    private javax.swing.JButton buttonSimpanBobotW;
    private javax.swing.JButton buttonSimpanDataHasilPengujian1;
    private javax.swing.JFileChooser fileChooserOpenFileMasukan;
    private javax.swing.JFileChooser fileChooserSaveBoborV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel labelBobotV;
    private javax.swing.JLabel labelBobotV1;
    private javax.swing.JLabel labelBobotW;
    private javax.swing.JLabel labelBobotW1;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelHiddenLayer;
    private javax.swing.JLabel labelJumlahIterasi;
    private javax.swing.JLabel labelKecepatanBelajar;
    private javax.swing.JLabel labelMinimumError;
    private javax.swing.JTextArea textAreaHasilPengujian;
    private javax.swing.JTextArea textAreaMasukanPembelajaran;
    private javax.swing.JTextArea textAreaMasukanPengujian;
    private javax.swing.JTextArea textAreaTargetPembelajaran;
    private javax.swing.JTextArea textAreaTargetPengujian;
    private javax.swing.JTextField textFieldBobotV;
    private javax.swing.JTextField textFieldBobotVPengujian;
    private javax.swing.JTextField textFieldBobotW;
    private javax.swing.JTextField textFieldBobotWPengujian;
    private javax.swing.JTextField textFieldDataMasukanPengujian;
    private javax.swing.JTextField textFieldDataTargetPengujian;
    private javax.swing.JTextField textFieldError;
    private javax.swing.JTextField textFieldHiddenLayer;
    private javax.swing.JTextField textFieldJumlahIterasi;
    private javax.swing.JTextField textFieldKecepatanBelajar;
    private javax.swing.JTextField textFieldLocationMasukanPembelajaran;
    private javax.swing.JTextField textFieldLocationMasukanTarget;
    private javax.swing.JTextField textFieldLokasiDataHasilPengujian;
    private javax.swing.JTextField textFieldMinimumError;
    // End of variables declaration//GEN-END:variables
}
